## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

# This function creates a special "matrix" object that can cache its inverse.
# this is a blueprint or anomy of Object in OOP that has it's param and functions
makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL # var to hold the inverse value of the matrix
  
  set <- function(new_val) {
    x <- new_val # update the new value
    inv <- NULL # invalidate the old one
  }
  
  get <- function() {
    x # get the value of x
  }
  
  setInverse <- function(val) {
    inv <- val # set the inverse value
  }
  
  getInverse <- function() {
    inv # get the value of inv
  }
  
  # return object methods (OOP static methods to call)
  list(
    set = set,
    get = get,
    setInverse = setInverse,
    getInverse = getInverse
  )
}


## Write a short comment describing this function

# This function is used to work with matrix that generated by makeCacheMatrix.
# (Analogy of OOP Instantiation of the object)
# If the inveser already been calcualted, and the matrix is the same,
# then we just return the cached value instead of recalculating it.

cacheSolve <- function(x, ...) {
  inv <- x$getInverse() # try to retrieve the cached inverse
  
  if (!is.null(inv)) {
    # we are able to retrieve inverse from cache
    return(inv)
  }
  
  # cache dose not have the inverse
  data <- x$get() # get the actual matrix data that stored in the x
  inv <-
    solve(data, ...) # If you pass a square matrix A to the solve() function like solve(A)
  x$setInverse(inv) # then we want to cache the calculation result
  return(inv)
}



# how to test the code? 
# A = matrix(c(4, 7, 2, 6), nrow = 2) # create an inversible matrix
# solve(A) # get matrix inverse in a normal way 

# now compare the result with the functions aboe
# cacheSolve(
# makeCacheMatrix(A)
# )

# the results are same. ✅

# [,1] [,2]
# [1,]  0.6 -0.2
# [2,] -0.7  0.4
